version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: budget-postgres
    environment:
      POSTGRES_DB: budget_app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ivan
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: budget-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/budget_app
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: ivan
    depends_on:
      - postgres

volumes:
  postgres_data: